export interface Framework {
  id: string;
  name: string;
  category: 'web' | 'mobile' | 'desktop' | 'cli' | 'backend';
  cliCommand: string;
  cliArgs?: string[];
  packageManager: 'bun' | 'npm' | 'yarn' | 'pnpm' | 'flutter' | 'deno' | 'cargo' | 'go' | 'none';
  popularity: number; // 1-10, used for weighted randomization
  stability: number; // 1-10, used for weighted randomization
  compatibleLibraries: string[];
  builtInTemplates?: string[];
  gitTemplateSources?: string[];
  postInstallCommands?: string[];
}

export const FRAMEWORKS: Framework[] = [
  // Web Frameworks
  {
    id: 'react-vite',
    name: 'React (Vite)',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'vite', '{projectName}', '--template', 'react'],
    packageManager: 'bun',
    popularity: 10,
    stability: 10,
    compatibleLibraries: [
      'react-router-dom',
      'axios',
      'zustand',
      'tailwindcss',
      'framer-motion',
      'react-query',
    ],
    builtInTemplates: ['basic', 'with-router', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'next-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 10,
    stability: 10,
    compatibleLibraries: ['next-auth', 'prisma', 'tailwindcss', 'framer-motion', 'react-query'],
    builtInTemplates: ['basic', 'with-tailwind', 'with-prisma'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'vue-vite',
    name: 'Vue (Vite)',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'vite', '{projectName}', '--template', 'vue'],
    packageManager: 'bun',
    popularity: 8,
    stability: 9,
    compatibleLibraries: ['vue-router', 'pinia', 'axios', 'tailwindcss'],
    builtInTemplates: ['basic', 'with-router', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'nuxt',
    name: 'Nuxt',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'nuxt-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 8,
    stability: 9,
    compatibleLibraries: ['@nuxtjs/tailwindcss', '@pinia/nuxt', '@nuxtjs/axios'],
    builtInTemplates: ['basic', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'svelte',
    name: 'Svelte',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'vite', '{projectName}', '--template', 'svelte'],
    packageManager: 'bun',
    popularity: 7,
    stability: 8,
    compatibleLibraries: ['svelte-routing', 'svelte-store', 'axios', 'tailwindcss'],
    builtInTemplates: ['basic', 'with-router', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'solid',
    name: 'SolidJS',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'solid', '{projectName}'],
    packageManager: 'bun',
    popularity: 5,
    stability: 7,
    compatibleLibraries: ['@solidjs/router', 'solid-js', 'axios', 'tailwindcss'],
    builtInTemplates: ['basic', 'with-router', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'angular',
    name: 'Angular',
    category: 'web',
    cliCommand: 'ng',
    cliArgs: ['new', '{projectName}'],
    packageManager: 'npm',
    popularity: 7,
    stability: 9,
    compatibleLibraries: ['@angular/router', '@angular/common', 'rxjs'],
    builtInTemplates: ['basic'],
    postInstallCommands: ['npm install'],
  },

  // Mobile Frameworks
  {
    id: 'react-native',
    name: 'React Native',
    category: 'mobile',
    cliCommand: 'bun',
    cliArgs: ['create', 'react-native-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 9,
    stability: 8,
    compatibleLibraries: [
      '@react-navigation/native',
      'react-native-maps',
      'axios',
      '@react-native-async-storage/async-storage',
    ],
    builtInTemplates: ['basic', 'with-navigation'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'expo',
    name: 'Expo',
    category: 'mobile',
    cliCommand: 'bun',
    cliArgs: ['create', 'expo-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 9,
    stability: 9,
    compatibleLibraries: ['expo-router', 'expo-location', 'axios', 'expo-secure-store'],
    builtInTemplates: ['basic', 'with-router', 'with-tabs'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'expo-stack',
    name: 'Expo Stack',
    category: 'mobile',
    cliCommand: 'bun',
    cliArgs: ['create', 'expo-stack-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 8,
    stability: 8,
    compatibleLibraries: ['expo-router', 'expo-location', 'axios', 'expo-secure-store', 'solito'],
    builtInTemplates: ['basic', 'with-router', 'with-tabs'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'flutter',
    name: 'Flutter',
    category: 'mobile',
    cliCommand: 'flutter',
    cliArgs: ['create', '{projectName}'],
    packageManager: 'flutter',
    popularity: 9,
    stability: 10,
    compatibleLibraries: ['provider', 'http', 'shared_preferences', 'flutter_bloc'],
    builtInTemplates: ['basic', 'with-state'],
    postInstallCommands: ['flutter pub get'],
  },

  // Desktop Frameworks
  {
    id: 'tauri',
    name: 'Tauri',
    category: 'desktop',
    cliCommand: 'bun',
    cliArgs: ['create', 'tauri-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 7,
    stability: 8,
    compatibleLibraries: ['react', 'vue', 'svelte', 'solid-js', 'axios'],
    builtInTemplates: ['basic', 'with-react', 'with-vue'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'electron',
    name: 'Electron',
    category: 'desktop',
    cliCommand: 'bun',
    cliArgs: ['create', 'electron-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 8,
    stability: 9,
    compatibleLibraries: ['electron', 'electron-builder', 'axios'],
    builtInTemplates: ['basic', 'with-react'],
    postInstallCommands: ['bun install'],
  },

  // CLI/Terminal Frameworks
  {
    id: 'ink',
    name: 'Ink (React CLI)',
    category: 'cli',
    cliCommand: 'bun',
    cliArgs: ['create', 'ink-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 6,
    stability: 7,
    compatibleLibraries: ['ink', 'ink-table', 'ink-spinner', 'axios'],
    builtInTemplates: ['basic', 'with-tables'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'tui',
    name: 'TUI Framework',
    category: 'cli',
    cliCommand: 'bun',
    cliArgs: ['create', 'tui-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 5,
    stability: 6,
    compatibleLibraries: ['blessed', 'chalk', 'ora', 'inquirer'],
    builtInTemplates: ['basic', 'with-forms'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'deno-cli',
    name: 'Deno CLI',
    category: 'cli',
    cliCommand: 'deno',
    cliArgs: ['init', '{projectName}'],
    packageManager: 'deno',
    popularity: 6,
    stability: 7,
    compatibleLibraries: ['std', 'cliffy', 'oak'],
    builtInTemplates: ['basic', 'with-server'],
    postInstallCommands: [],
  },

  // Backend Frameworks
  {
    id: 'deno',
    name: 'Deno',
    category: 'backend',
    cliCommand: 'deno',
    cliArgs: ['init', '{projectName}'],
    packageManager: 'deno',
    popularity: 7,
    stability: 8,
    compatibleLibraries: ['oak', 'std', 'postgres'],
    builtInTemplates: ['basic', 'with-oak', 'with-postgres'],
    postInstallCommands: [],
  },
  {
    id: 'bun-backend',
    name: 'Bun Backend',
    category: 'backend',
    cliCommand: 'bun',
    cliArgs: ['create', 'bun-backend', '{projectName}'],
    packageManager: 'bun',
    popularity: 8,
    stability: 8,
    compatibleLibraries: ['elysia', 'drizzle-orm', 'postgres', 'zod'],
    builtInTemplates: ['basic', 'with-elysia', 'with-drizzle'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'node-express',
    name: 'Node.js Express',
    category: 'backend',
    cliCommand: 'bun',
    cliArgs: ['create', 'express-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 9,
    stability: 10,
    compatibleLibraries: ['express', 'mongoose', 'cors', 'dotenv'],
    builtInTemplates: ['basic', 'with-mongo', 'with-sql'],
    postInstallCommands: ['bun install'],
  },
  // Additional Web Frameworks
  {
    id: 'sveltekit',
    name: 'SvelteKit',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'sveltekit', '{projectName}'],
    packageManager: 'bun',
    popularity: 9,
    stability: 9,
    compatibleLibraries: ['@sveltejs/adapter-auto', 'svelte-preprocess', 'tailwindcss'],
    builtInTemplates: ['basic', 'with-skeleton', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'astro',
    name: 'Astro',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'astro', '{projectName}'],
    packageManager: 'bun',
    popularity: 8,
    stability: 9,
    compatibleLibraries: ['@astrojs/react', '@astrojs/vue', '@astrojs/tailwind'],
    builtInTemplates: ['basic', 'with-react', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'remix',
    name: 'Remix',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'remix', '{projectName}'],
    packageManager: 'bun',
    popularity: 8,
    stability: 8,
    compatibleLibraries: ['@remix-run/node', '@remix-run/react', 'prisma'],
    builtInTemplates: ['basic', 'with-prisma', 'with-tailwind'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'solidstart',
    name: 'SolidStart',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'solid-start', '{projectName}'],
    packageManager: 'bun',
    popularity: 6,
    stability: 7,
    compatibleLibraries: ['solid-js', '@solidjs/router', 'vinxi'],
    builtInTemplates: ['basic', 'with-router'],
    postInstallCommands: ['bun install'],
  },
  // Additional Mobile Frameworks
  {
    id: 'ionic',
    name: 'Ionic',
    category: 'mobile',
    cliCommand: 'bun',
    cliArgs: ['create', 'ionic-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 7,
    stability: 8,
    compatibleLibraries: ['@ionic/react', '@ionic/angular', 'capacitor'],
    builtInTemplates: ['basic', 'with-react', 'with-angular'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'capacitor',
    name: 'Capacitor',
    category: 'mobile',
    cliCommand: 'bun',
    cliArgs: ['create', 'capacitor-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 7,
    stability: 8,
    compatibleLibraries: ['@capacitor/core', '@capacitor/android', '@capacitor/ios'],
    builtInTemplates: ['basic', 'with-react', 'with-vue'],
    postInstallCommands: ['bun install'],
  },
  // Additional Desktop Frameworks
  {
    id: 'neutralino',
    name: 'Neutralino',
    category: 'desktop',
    cliCommand: 'bun',
    cliArgs: ['create', 'neutralino-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 5,
    stability: 6,
    compatibleLibraries: ['@neutralinojs/lib', 'react', 'vue'],
    builtInTemplates: ['basic', 'with-react', 'with-vue'],
    postInstallCommands: ['bun install'],
  },
  // Additional CLI Frameworks
  {
    id: 'clack',
    name: 'Clack',
    category: 'cli',
    cliCommand: 'bun',
    cliArgs: ['create', 'clack-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 6,
    stability: 7,
    compatibleLibraries: ['@clack/prompts', '@clack/core', 'picocolors'],
    builtInTemplates: ['basic', 'with-forms', 'with-animations'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'cliffy',
    name: 'Cliffy',
    category: 'cli',
    cliCommand: 'deno',
    cliArgs: ['run', 'https://deno.land/x/cliffy/command/create.ts', '{projectName}'],
    packageManager: 'deno',
    popularity: 6,
    stability: 7,
    compatibleLibraries: ['std', 'cliffy/command', 'cliffy/prompts'],
    builtInTemplates: ['basic', 'with-commands', 'with-arguments'],
    postInstallCommands: [],
  },
  // Additional Backend Frameworks
  {
    id: 'fastify',
    name: 'Fastify',
    category: 'backend',
    cliCommand: 'bun',
    cliArgs: ['create', 'fastify-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 8,
    stability: 9,
    compatibleLibraries: ['fastify', '@fastify/cors', '@fastify/swagger'],
    builtInTemplates: ['basic', 'with-swagger', 'with-typeorm'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'koa',
    name: 'Koa',
    category: 'backend',
    cliCommand: 'bun',
    cliArgs: ['create', 'koa-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 7,
    stability: 9,
    compatibleLibraries: ['koa', '@koa/router', 'koa-bodyparser'],
    builtInTemplates: ['basic', 'with-router', 'with-middleware'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'hono',
    name: 'Hono',
    category: 'backend',
    cliCommand: 'bun',
    cliArgs: ['create', 'hono-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 7,
    stability: 8,
    compatibleLibraries: ['hono', '@hono/zod-validator', 'zod'],
    builtInTemplates: ['basic', 'with-zod', 'with-middleware'],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'nestjs',
    name: 'NestJS',
    category: 'backend',
    cliCommand: 'bun',
    cliArgs: ['create', 'nestjs-app', '{projectName}'],
    packageManager: 'bun',
    popularity: 9,
    stability: 10,
    compatibleLibraries: ['@nestjs/common', '@nestjs/core', '@nestjs/typeorm'],
    builtInTemplates: ['basic', 'with-typeorm', 'with-graphql'],
    postInstallCommands: ['bun install'],
  },
  // Git Template Sources
  {
    id: 'vite-react-ts',
    name: 'Vite React TypeScript',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'vite', '{projectName}', '--template', 'react-ts'],
    packageManager: 'bun',
    popularity: 9,
    stability: 10,
    compatibleLibraries: ['react-router-dom', 'axios', 'zustand', 'tailwindcss'],
    builtInTemplates: ['basic'],
    gitTemplateSources: [
      'https://github.com/vitejs/vite/tree/main/packages/create-vite/template-react-ts',
    ],
    postInstallCommands: ['bun install'],
  },
  {
    id: 'next-starter',
    name: 'Next.js Starter',
    category: 'web',
    cliCommand: 'bun',
    cliArgs: ['create', 'next-app', '{projectName}', '--typescript', '--tailwind', '--eslint'],
    packageManager: 'bun',
    popularity: 10,
    stability: 10,
    compatibleLibraries: ['next-auth', 'prisma', 'framer-motion'],
    builtInTemplates: ['basic'],
    gitTemplateSources: [
      'https://github.com/vercel/next.js/tree/canary/packages/create-next-app/templates/ts',
    ],
    postInstallCommands: ['bun install'],
  },
];

export function getFrameworkById(id: string): Framework | undefined {
  return FRAMEWORKS.find((f) => f.id === id);
}

export function getFrameworksByCategory(category: Framework['category']): Framework[] {
  return FRAMEWORKS.filter((f) => f.category === category);
}

export function getAllCategories(): Framework['category'][] {
  return [...new Set(FRAMEWORKS.map((f) => f.category))];
}
